kccistc/intel-02

- README.md
- doc/environment/openvino.md
- doc/environment/otx.md
- doc/environment/ubuntu.md
> issue #1 : Added guidance for environment

- class01/homework/yeongdaeKim/README.md
- class02/homework/yeongdaeKim/README.md
> [yeongdaeKim] the 2nd assignment : HW2-yeongdaeKim-roby238

- class01/homework/AhnSoegHyun/02_camera.py
- class01/homework/AhnSoegHyun/03_camera.py
add 02.carema.py & add 03.camera.py
> [AhnSeogHyun] Class01 HW3 OpenCV assignment

- class01/homework/gyuseungseo/02_camera.py
- class01/homework/gyuseungseo/03_camera.py
> [Gyuseung Seo] Class01 HW3 OpenCV assignment

- class01/homework/jonghyeokOh/02_camera.py
> [Jonghyeok, Oh] Class01 HW3 OpenCV assignment

- class01/homework/KimJinho/hw3/02_camera.py
- class01/homework/KimJinho/hw3/03_camera.py
add homework #1, #2
02.camera.py, 03,camera.py
> [Jinho Kim]Class01 HW3 OpenCV assignment 

- class01/homework/jeonginseong/hw3/HW3_1_answer.py
- class01/homework/jeonginseong/hw3/HW3_2_answer.py
2023.10.28
opencv hw3
answer1
answer2
> [INseong Jeong] the 3rd homework

- class01/homework/yeongdaeKim/hw3/homework_opencv_1.py
- class01/homework/yeongdaeKim/hw3/homework_opencv_2.py
> [yeongdaeKim] Class01 HW3 OpenCV assignment 

- class01/homework/YurimLee/README.md
- class01/homework/YurimLee/hw3/02_camera_yurim.py
- class01/homework/YurimLee/hw3/03_camera_yurim.py
Homework 1 : `02_camera_yurim.py`
Homework 2 : `03_camera_yurim.py`
> [Yurim Lee] the 3rd homework

- class01/homework/NayeongYu/opencv_hw1_ny.py
- class01/homework/NayeongYu/opencv_hw2_ny.py
homework1 : opencv_hw1_ny.py
homework2: opencv_hw2_ny.py
> [Nayeong Yu] opencv homework1,2

- class01/homework/SuengkwonYu/hw03/02_camera.py
- class01/homework/SuengkwonYu/hw03/03_camera.py
[SuengkwonYu] class01 OpenCV Assignment
>  [SuengkwonYu] class01 OpenCV Assignment

- class01/homework/SuengkwonYu/hw04/404-style-transfer.py
- class01/homework/SuengkwonYu/hw04/README.md
>  [Suengkwon Yu] OpenCV HW#4

- class01/homework/AhnSoegHyun/hw3/02_camera.py
- class01/homework/AhnSoegHyun/hw3/03_camera.py
- class01/homework/AhnSoegHyun/hw4/README.md
- class01/homework/AhnSoegHyun/hw4/hw4.py
- class01/homework/AhnSoegHyun/hw4/requirements.txt
add hw4.py, requirment.txt, README.md
> [AhnSeogHyun] Class01 HW4 OpenCV assignment

- class01/homework/gyuseungseo/hw3/02_camera.py
- class01/homework/gyuseungseo/hw3/03_camera.py
- class01/homework/gyuseungseo/hw4/README.md
- class01/homework/gyuseungseo/hw4/style_trans.py
1. fix hw3
2. add hw4/style_trans.py
> [gyuseung seo] Class01 HW4 OpenCV Assignment

- class02/homework/KimJinho/hw1/led.py
Arduino와 연결한 빵판에 LED 회로를 구성하고 Python으로 LED를 제어하는 코드를 제출
Input 값에 따른 API 호출 코드를 작성
실제 해당하는 API에 LED가 ON/OFF 되는지 확인
[API Table](https://github.com/jerry-jaeseong-lee/temp/assets/26781272/6770f40d-e0b3-4f51-9253-7bac25739b69)
[빵판 구성](https://github.com/jerry-jaeseong-lee/temp/assets/26781272/ff24e0a1-b762-4303-8c44-416b14eee59c)
제출
<root_dir>/class02/homework/<내이름>/hw1/led.py
> Class02 과제1 Arduino와 Python을 이용한 LED 제어 - JinhoKim

- class02/homework/SuengkwonYu/hw1/led.py
Arduino와 연결한 빵판에 LED 회로를 구성하고 Python으로 LED를 제어하는 코드를 제출
Input 값에 따른 API 호출 코드를 작성
실제 해당하는 API에 LED가 ON/OFF 되는지 확인
[API Table](https://github.com/jerry-jaeseong-lee/temp/assets/26781272/6770f40d-e0b3-4f51-9253-7bac25739b69)
[빵판 구성](https://github.com/jerry-jaeseong-lee/temp/assets/26781272/ff24e0a1-b762-4303-8c44-416b14eee59c)
제출
<root_dir>/class02/homework/<내이름>/hw1/led.py
> Class02 과제1 Arduino와 Python을 이용한 LED 제어 - Suengkwon Yu

- class02/homework/KimJinho/hw1/led.py
- class02/homework/KimJinho/hw2/factory.py
과제:
두개의 비디오 입력을 받아들이는 thread thread_cam1, thread_cam2를 구현하고 queue로 live camera frame정보를 전달.
비디오는 resources/conveyor.mp4에 있음.
Main thread에서 queue를 검사해서 thread로 부터의 입력이 있으면 각각을 Cam1 live와 Cam2 live 창으로 출력해야 함.
제출
<root_dir>/class02/smart_factory/factory.py를 참조하여 작성
class02/homework/<내이름>/hw2/factory.py에 코드만 작성하고 PR을 생성
> Class02 과제2 멀티쓰레딩 카메라 출력 구현 - JinhoKim

- class02/homework/najunhee/hw1/led.py
> Class02 HW1 Najunhee

- class02/homework/yeongdaeKim/hw1/led.py
uploaded led.py
details for homework: control with each case
input 1 -> system start
input 2 -> system stop
input 3 -> red status toggled
input 4 -> orange status toggled
input 5 -> green status toggled
input 6 -> conveyor status toggled
input 7 -> button 1 pressed
input 8 -> button 2 pressed
> [yeongdaeKim] CLASS02 HW1 upload v1

- class02/homework/YoungsikCho/hw1/led.py
- class02/homework/YoungsikCho/hw2/factory.py
>  Class02 과제2 멀티쓰레딩 카메라 출력 구현 - 조영식

- class02/homework/YoungsikCho/hw1/led.py
> Class02 과제1 Arduino와 Python을 이용한 LED 제어 - 조영식

- class02/homework/SuengkwonYu/hw1/led.py
- class02/homework/SuengkwonYu/hw2/factory.py
자기 이름의 issue ticket을 생성
e.g) 과제2 멀티쓰레딩 카메라 출력 구현 - <내이름>
Issue ticket을 자기에게 할당 assign yourself.
Milestone을 Class02 과제2 멀티쓰레딩 카메라 출력 구현으로 설정
과제:
두개의 비디오 입력을 받아들이는 thread thread_cam1, thread_cam2를 구현하고 queue로 live camera frame정보를 전달.
비디오는 resources/conveyor.mp4에 있음.
Main thread에서 queue를 검사해서 thread로 부터의 입력이 있으면 각각을 Cam1 live와 Cam2 live 창으로 출력해야 함.
>  Class02 과제2 멀티쓰레딩 카메라 출력 구현 - Suengkwon Yu

- class02/homework/YurimLee/hw1/led.py
`led.py`
(조건 : [API Table](https://github.com/jerry-jaeseong-lee/temp/assets/26781272/6770f40d-e0b3-4f51-9253-7bac25739b69))
> Class02 과제1 Arduino와 Python을 이용한 LED 제어 - 이유림

- class02/homework/najunhee/hw2/factory.py
> Class02-HW2-NJH

- class02/homework/yeongdaeKim/hw2/factory.py
modifieded factory.py
details for homework:
1. make a queue
- remove join
2. add two threads with the queue
3. open video
4. enqueue a name(cam info) and a frame from video into the queue
- change name from PUSH to cam_info
5. dequeue infos(name and frame) from the queue in main func
- remove mutex
6. show frames at the each window(cam1_live and cam2_live)
- show video with name
> [yeongdaeKim] CLASS02 HW2 uploaded

- class02/homework/gyuseungseo/hw1/led.py
> Class02 과제1 Arduino와 Python을 이용한 LED 제어 - 서규승

- class02/homework/jeonginseong/hw1/led.py
<root_dir>/class02/homework/<내이름>/hw1/led.py
> Class02 과제1 Arduino와 Python을 이용한 LED 제어 - 정인성

- class02/homework/ParkYoungMoon/hw1/led.py
<root_dir>/class02/homework/<내이름>/hw1/led.py
>  Class02 과제1 Arduino와 Python을 이용한 LED 제어 - ParkYoungMoon

- class02/homework/hyeanhongAn/hw1/led.py
- class02/homework/hyeanhongAn/hw2/factory.py
class 02 HW1 , HW2  simpleis6est
add led.py, factory_my.py
add dir hw1, hw2, hw3, final
>  Class02 과제1,2 - anhyeanhong(simpleis6est) 

- class02/homework/gyuseungseo/hw2/factory.py
> Class02 과제2 멀티쓰레딩 카메라 출력 구현 - 서규승

- class02/homework/Gwonchungu/hw2/factory.py
과제:
두개의 비디오 입력을 받아들이는 thread thread_cam1, thread_cam2를 구현하고 queue로 live camera frame정보를 전달.
비디오는 resources/conveyor.mp4에 있음.
Main thread에서 queue를 검사해서 thread로 부터의 입력이 있으면 각각을 Cam1 live와 Cam2 live 창으로 출력해야 함.
제출
<root_dir>/class02/smart_factory/factory.py를 참조하여 작성
class02/homework/<내이름>/hw2/factory.py에 코드만 작성하고 PR을 생성
> Class02 과제2 멀티쓰레딩 카메라 출력 구현 - 권춘구(수정)

- class02/homework/jonghyeokOh/hw1/led.py
> Class02 과제1 Arduino와 Python을 이용한 LED 제어 - 오종혁

- class02/homework/jonghyeokOh/hw3/DeiT-Tiny/openvino.bin
- class02/homework/jonghyeokOh/hw3/DeiT-Tiny/openvino.xml
- class02/homework/jonghyeokOh/hw3/EfficientNet-B0/openvino.bin
- class02/homework/jonghyeokOh/hw3/EfficientNet-B0/openvino.xml
- class02/homework/jonghyeokOh/hw3/EfficientNet-V2-S/openvino.bin
- class02/homework/jonghyeokOh/hw3/EfficientNet-V2-S/openvino.xml
- class02/homework/jonghyeokOh/hw3/Mobile-V3-large-1x/openvino.bin
- class02/homework/jonghyeokOh/hw3/Mobile-V3-large-1x/openvino.xml
- class02/homework/jonghyeokOh/hw3/README.md
> Class02 과제3 OTX를 이용한 model training - 오종혁

- class02/homework/AhnSeogHyun/hw3/DeiT-Tiny/openvino.bin
- class02/homework/AhnSeogHyun/hw3/DeiT-Tiny/openvino.xml
- class02/homework/AhnSeogHyun/hw3/EfficientNet-B0/openvino.bin
- class02/homework/AhnSeogHyun/hw3/EfficientNet-B0/openvino.xml
- class02/homework/AhnSeogHyun/hw3/EfficientNet-V2-S/openvino.bin
- class02/homework/AhnSeogHyun/hw3/EfficientNet-V2-S/openvino.xml
- class02/homework/AhnSeogHyun/hw3/MobileNet-V3-large-1x/openvino.bin
- class02/homework/AhnSeogHyun/hw3/MobileNet-V3-large-1x/openvino.xml
- class02/homework/AhnSeogHyun/hw3/README.md
add hw3 objects and README.md
models.xml
models.bin
> Class02 과제3 OTX를 이용한 model training - 안석현

- class02/homework/YoungsikCho/hw3/DeiT-Tiny/openvino.bin
- class02/homework/YoungsikCho/hw3/DeiT-Tiny/openvino.xml
- class02/homework/YoungsikCho/hw3/EfficientNet-B0/openvino.bin
- class02/homework/YoungsikCho/hw3/EfficientNet-B0/openvino.xml
- class02/homework/YoungsikCho/hw3/EfficientNet-V2-S/openvino.bin
- class02/homework/YoungsikCho/hw3/EfficientNet-V2-S/openvino.xml
- class02/homework/YoungsikCho/hw3/MobileNet-V3-large-1x/openvino.bin
- class02/homework/YoungsikCho/hw3/MobileNet-V3-large-1x/openvino.xml
- class02/homework/YoungsikCho/hw3/README.md
> 과제3 OTX를 이용한 model training - 조영식

- class02/homework/SuengkwonYu/hw3/DeiT-Tiny/openvino.xml
- class02/homework/SuengkwonYu/hw3/EfficientNet-B0/openvino.xml
- class02/homework/SuengkwonYu/hw3/EfficientNet-V2-S/openvino.xml
- class02/homework/SuengkwonYu/hw3/MobileNet-V3-large-1x/openvino.xml
- class02/homework/SuengkwonYu/hw3/README.md
제출
<root_dir>/class02/homework/hw03_template.md를 내 과제 디렉토리에 README.md로 복사
mkdir -p intel-02/class02/homework/<내이름>/hw3 && cd $_
cp ../../hw03_template.md ./hw3/README.md 
새로운 workspace를 만들고 tool로 수집한 dataset으로 불량 분류 모델을 otx로 raining
결과물 IR(xml, bin)을 찾아서 hw3/<model_name>/안에 복사
splitted_dataset의 ds_count ./splitted_dataset 2결과를 Dataset 구조에 작성
4개의 classification model들을 training하고 정확도, FPS, training 소요시간, 사용한 batch 크기, learning rate, 추가로 조절한 parameter들을 테이블로 작성.
FPS를 어떻게 측정했는지를 기술
생성한 PR의 Development 항목에 생성한 issue를 link
> 과제3 OTX를 이용한 model training - Suengkwon Yu

- class02/homework/najunhee/hw3/DeiT-Tiny/openvino.bin
- class02/homework/najunhee/hw3/DeiT-Tiny/openvino.xml
- class02/homework/najunhee/hw3/EfficientNet-B0/openvino.bin
- class02/homework/najunhee/hw3/EfficientNet-B0/openvino.xml
- class02/homework/najunhee/hw3/EfficientNet-V2-S/openvino.bin
- class02/homework/najunhee/hw3/EfficientNet-V2-S/openvino.xml
- class02/homework/najunhee/hw3/MobileNet-V3-large-1x/openvino.bin
- class02/homework/najunhee/hw3/MobileNet-V3-large-1x/openvino.xml
- class02/homework/najunhee/hw3/README.md
> Class02 hw3 na jun hee

- class02/homework/JooeunPark/hw2/factory.py
과제:
두개의 비디오 입력을 받아들이는 thread thread_cam1, thread_cam2를 구현하고 queue로 live camera frame정보를 전달.
비디오는 resources/conveyor.mp4에 있음.
Main thread에서 queue를 검사해서 thread로 부터의 입력이 있으면 각각을 Cam1 live와 Cam2 live 창으로 출력해야 함.
제출
<root_dir>/class02/smart_factory/factory.py를 참조하여 작성
class02/homework/<내이름>/hw2/factory.py에 코드만 작성하고 PR을 생성
> Class02 과제2 멀티쓰레딩 카메라 출력 구현 - JooeunPark

- class02/homework/Gwonchungu/final/factory.py
과제:
지금 까지 수행한 Arduino control, multi threading, model training 결과물을 합쳐서 다음의 기능을 수행하는 factory.py 파일을 작성
resources/conveyor.mp4 입력을 받음
thread_cam1 thread에서 frame을 입력 받아 inference 수행하여 양품/불량품을 구분
불량품인 경우 actuator 1을 'kick'하는 Arduino API 호출
thread_cam2 thread에서 frame을 입력 받아 흰색/파란색 구분
파란색인 경우 actuator 2를 kick하는 Arduio API 호출
제출
class02/homework/<내이름>/final/factory.py에 코드를 작성하여 PR을 생성
> 과제4 Smart factory 최종 구현 - 권춘구

- class02/homework/JooeunPark/hw4/factory_je.py
* 과제:
* 지금 까지 수행한 Arduino control, multi threading, model training 결과물을 합쳐서 다음의 기능을 수행하는 `factory.py` 파일을 작성
* resources/conveyor.mp4 입력을 받음
* `thread_cam1` thread에서 frame을 입력 받아 inference 수행하여 양품/불량품을 구분
* 불량품인 경우 actuator 1을 'kick'하는 Arduino API 호출
* `thread_cam2` thread에서 frame을 입력 받아 흰색/파란색 구분
* 파란색인 경우 actuator 2를 `kick`하는 Arduio API 호출
* 제출
* class02/homework/<내이름>/final/factory.py에 코드를 작성하여 PR을 생성
* 생성된 PR의 Development 항목에 생성한 issue를 link
* 지정된 reviewer를 할당
* 주의: smart_factory내의 파일은 수정하지 말것
> 과제4 Smart factory 최종 구현 - JooeunPark

- class02/homework/YoungsikCho/final/factory.py
과제:
지금 까지 수행한 Arduino control, multi threading, model training 결과물을 합쳐서 다음의 기능을 수행하는 factory.py 파일을 작성
resources/conveyor.mp4 입력을 받음
thread_cam1 thread에서 frame을 입력 받아 inference 수행하여 양품/불량품을 구분
불량품인 경우 actuator 1을 'kick'하는 Arduino API 호출
thread_cam2 thread에서 frame을 입력 받아 흰색/파란색 구분
파란색인 경우 actuator 2를 kick하는 Arduio API 호출
제출
class02/homework/<내이름>/final/factory.py에 코드를 작성하여 PR을 생성
> 과제4 Smart factory 최종 구현 - 조영식

- class02/homework/yeongdaeKim/hw4/factory.py
uploaded factory.py
Details:
1. I selected ROI using iotdemo-motion-detector tool and saved as motion.cfg.
2. I generated two classes('white' and 'blue') using iotdemo-color-detector tool and saved as color.cfg.
3. Thread1 
- Detect frame. 
- Using DT model, guess that it is X or Circle. 
- Print ratio. 
- Enqueue ('PUSH', 1) to q.
4. Thread2 
- Detect frame 
- Determinate color. 
- Print ratio. 
- Enqueue ('PUSH', 2) to q.
5. Main : dequeue data(name, frame) from q. 
- If name is 'PUSH', run actuator.
- If name is 'DONE', flag off. Finish the loop.
- If name is 'VIDEO...', show the frame.
6. Results :     
- ratio
> [yeongdaeKim] CLASS02 Smart factory Final upload

- class02/homework/KimJinho/final/factory.py
과제:
지금 까지 수행한 Arduino control, multi threading, model training 결과물을 합쳐서 다음의 기능을 수행하는 factory.py 파일을 작성
resources/conveyor.mp4 입력을 받음
thread_cam1 thread에서 frame을 입력 받아 inference 수행하여 양품/불량품을 구분
불량품인 경우 actuator 1을 'kick'하는 Arduino API 호출
thread_cam2 thread에서 frame을 입력 받아 흰색/파란색 구분
파란색인 경우 actuator 2를 kick하는 Arduio API 호출
제출
class02/homework/<내이름>/final/factory.py에 코드를 작성하여 PR을 생성
> 과제4 Smart factory 최종 구현 - JinhoKim

- README.md
Add team01(Board Maestro) project info
> [TEAM01] Update README.md with team01 project info

- README.md
< Team03 project info >
- title : `Z:ERO (Zㅔ발 Eyes Re-Open)`
- desc : Driver Monitoring System and Autonomous Driving System
> [TEAM03] Update README.md : Team03(ZERO) project info added

- README.md
make git repository
update README.md
> [TEAM2] Update README.md : Team2 !(맛있으면 0kcal) project info added

- class02/homework/AhnSeogHyun/README.md
최종 과제가 용량 문제로 풀이 되지 않아서 개인 레포지토리에 업데이트하여 제출합니다.
같은 내용은 개인 과제 제출 디렉토리인 README.md에 업데이트 되어있습니다.
https://github.com/User3198352/my-project.git
> 과제4 Smart factory 최종 구현 - 안석현

- class02/homework/jonghyeokOh/final/factory.py
> 과제4 Smart factory 최종 구현 - 오종혁

- class02/homework/SuengkwonYu/final/factory.py
* 과제:
* 지금 까지 수행한 Arduino control, multi threading, model training 결과물을 합쳐서 다음의 기능을 수행하는 `factory.py` 파일을 작성
* resources/conveyor.mp4 입력을 받음
* `thread_cam1` thread에서 frame을 입력 받아 inference 수행하여 양품/불량품을 구분
* 불량품인 경우 actuator 1을 'kick'하는 Arduino API 호출
* `thread_cam2` thread에서 frame을 입력 받아 흰색/파란색 구분
* 파란색인 경우 actuator 2를 `kick`하는 Arduio API 호출
* 제출
* class02/homework/<내이름>/final/factory.py에 코드를 작성하여 PR을 생성
* 생성된 PR의 Development 항목에 생성한 issue를 link
* 지정된 reviewer를 할당
* 주의: smart_factory내의 파일은 수정하지 말것
> 과제4 Smart factory 최종 구현 - Suengkwon Yu

- class02/homework/EunYoungkim/README.md
> Class02 과제4 Smart factory 최종 구현 - EunYoungKim

- class02/homework/jeonginseong/final/factory.py
- class02/homework/jeonginseong/hw2/factory.py
- class02/homework/jeonginseong/hw3/DeiT-Tiny/openvino.bin
- class02/homework/jeonginseong/hw3/DeiT-Tiny/openvino.xml
- class02/homework/jeonginseong/hw3/EfficientNet-B0/openvino.bin
- class02/homework/jeonginseong/hw3/EfficientNet-B0/openvino.xml
- class02/homework/jeonginseong/hw3/EfficientNet-V2-S/openvino.bin
- class02/homework/jeonginseong/hw3/EfficientNet-V2-S/openvino.xml
- class02/homework/jeonginseong/hw3/MobileNet-V3-large-1x/openvino.bin
- class02/homework/jeonginseong/hw3/MobileNet-V3-large-1x/openvino.xml
- class02/homework/jeonginseong/hw3/README.md
resources/conveyor.mp4 입력을 받음
thread_cam1 thread에서 frame을 입력 받아 inference 수행하여 양품/불량품을 구분
불량품인 경우 actuator 1을 'kick'하는 Arduino API 호출
thread_cam2 thread에서 frame을 입력 받아 흰색/파란색 구분
파란색인 경우 actuator 2를 kick하는 Arduio API 호출
> Class02 과제4 Smart factory 최종 구현 - 정인성

- class02/homework/jeonginseong/hw2/factory.py
<root_dir>/class02/smart_factory/factory.py를 참조하여 작성
class02/homework/<내이름>/hw2/factory.py에 코드만 작성하고 PR을 생성
> Class02 과제2 멀티쓰레딩 카메라 출력 구현 - 정인성

- class02/homework/gyuseungseo/hw3/DeiT-Tiny/openvino.xml
- class02/homework/gyuseungseo/hw3/EfficientNet-B0/openvino.xml
- class02/homework/gyuseungseo/hw3/EfficientNet-V2-S/openvino.xml
- class02/homework/gyuseungseo/hw3/MobileNet-V3-large-1x/openvino.xml
- class02/homework/gyuseungseo/hw3/README.md
- class02/homework/gyuseungseo/hw4/README.md
add hw4/README.md
include github link
> 과제4 Smart factory 최종 구현 - 서규승

- class02/homework/gyuseungseo/hw3/DeiT-Tiny/openvino.xml
- class02/homework/gyuseungseo/hw3/EfficientNet-B0/openvino.xml
- class02/homework/gyuseungseo/hw3/EfficientNet-V2-S/openvino.xml
- class02/homework/gyuseungseo/hw3/MobileNet-V3-large-1x/openvino.xml
- class02/homework/gyuseungseo/hw3/README.md
add hw3/DeiT-Tiny
add hw3/EfficientNet-B0
add hw3/EfficientNet-V2-S
add hw3/MobileNet-V3-large-1x
add hw3/README.md
> 과제3 OTX를 이용한 model training - 서규승

- class02/homework/hyeanhongAn/README.md
git URL final READMe에 추가하여 pull request 를 합니다.
> Update README.md [final -git URL]

- class02/homework/hyeanhongAn/final/factory.py
add . factory.py
color.cfg ( detects only the blue color)
> final smart-factory [simpleis6est] 

- class02/homework/hyeanhongAn/hw3/DeiT-Tiny/openvino.bin
- class02/homework/hyeanhongAn/hw3/DeiT-Tiny/openvino.xml
- class02/homework/hyeanhongAn/hw3/EfficientNet-B0/openvino.bin
- class02/homework/hyeanhongAn/hw3/EfficientNet-B0/openvino.xml
- class02/homework/hyeanhongAn/hw3/EfficientNet-V2-S/openvino.bin
- class02/homework/hyeanhongAn/hw3/EfficientNet-V2-S/openvino.xml
- class02/homework/hyeanhongAn/hw3/MobileNet-V3-large-1x/openvino.bin
- class02/homework/hyeanhongAn/hw3/MobileNet-V3-large-1x/openvino.xml
- class02/homework/hyeanhongAn/hw3/hw03_template.md
> 과제3 OTX를 이용한 model training - anhyeanhong
